import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-lato antialiased bg-white text-navy">
        <header className="w-full flex flex-col items-center py-8 mb-8 border-b border-navy/10">
          <h1
            className="text-4xl font-bold tracking-wide text-navy uppercase"
            style={{ letterSpacing: "0.08em" }}
          >
            Saaftris
          </h1>
          <p className="mt-2 text-orange text-lg italic font-medium text-center max-w-xl">
            “I build quiet tools for a noisy world”
          </p>
        </header>
        {children}
      </body>
    </html>
  );
}
